### ISSUE TITLE
NullPointerException in administrative claims

### ISSUE THREAD

**Issue by Lammendam** [drbot7/GriefPreventionFlags#17]
**Describe the bug**
When I try to interact with containers (e.g. chest), I got `NullPointerException` ([pastebin](https://www.pastebin.com/ZS3v0WTV)).
It's only appears in administrative claims with `ViewContainers` flag, and it doesn't affect on player claims.

**To Reproduce**
Open any chest in any administrative claim with `ViewContainers` flag.

**Versions:**
 - GriefPrevention 16.18
 - GPFlags 5.11.2
 - Paper version git-Paper-388 (MC: 1.17.1)

**Comment by drbot7** [comment]
You can download the snapshot version at 
https://cdn.discordapp.com/attachments/751679912246771722/958180431168147476/GriefPreventionFlags-5.12.0-SNAPSHOT.jar

Changes since 5.11.3:
Requires Paper (or a fork)
Requires 1.18
Requires GP v16.18
+ Switched listlclaimflags to have verbose hover events
+ Fixed a NPE involving ViewContainers in admin claims
